#ifndef INITIAL_H_INCLUDED
#define INITIAL_H_INCLUDED

//排名不分先后
#define ERROR_TOOLONGIDEN 1 //TOO LONG IDENTIFIER
#define ERROR_NUMOVERFLOW 2 //NUMBER OVER FLOW
#define ERROR_TOOMANYCINSQ 3 // TOO MANY CHARACTER IN SINGLE QUOTE MARK
#define ERROR_INVLDCINSTR 4 //INVALID CHARACTER IN STRING
#define ERROR_TOOLONGSTR 5 //TOO LONG STRING
#define ERROR_INVLDEXC 6 //INVALID EXCLAMATORY MARK
#define ERROR_INVLDCINCD 7 //INVALID CHARACTER IN CODE
//error in gram
#define ERROR_GRAM 8 //GRAMMATICAL ERROR
#define ERROR_NZIBUTZERO 9 //NONZERO INTEGER BUT ZERO
#define ERROR_IDENREDCL 10 //IDENTIFIER REDECLARATION
//error in semantic analysis
#define ERROR_UNDCLIDEN 11 //UNDECLARED IDENTIFIER
#define ERROR_INVLDIDUSD 12 // INVALID IDENTIFER USED
#define ERROR_UNMTCHPARA 13 // UNMATCHED PARAMETER

//#define ERROR_INVLDCLIOC 8 //INVALID DECLARATION WHEN INT OR CHAR
//#define ERROR_INVLDCLVOID 9 //INVALID DECLARATION WHEN VOID

#endif // INITIAL_H_INCLUDED


//CopyRight by Librian